<div class="social-icons">
        <nav id="social">
            <ul>
				<li><a href="#" title="Sigame no Facebook" target="_blank"><span class="font-icon-social-facebook"></span></a></li>
                <li><a href="#" title="Sigame no Twitter" target="_blank"><span class="font-icon-social-twitter"></span></a></li>                
				<li><a href="#" title="" target="_blank"><span class="font-icon-heart"></span></a></li>
				<li><a href="#" title="Sigame no pinterest" target="_blank"><span class="font-icon-social-pinterest"></span></a></li>
                <li><a href="#" title="" target="_blank"><span class="font-icon-email"></span></a></li>                
            </ul>
           </nav>
    </div>